### ISSUE TITLE
server.py doesn't gracefully check channels format

### ISSUE THREAD

**Issue by dmiskovic-NV** [mlcommons/power-dev#154]
It might make sense to implement graceful checking and error message if tuple is passed as channel when used meter is not in multichannel mode (device type 52 for instance)
server log sample: 
```
ptd-server 2021-02-23 18:45:49,435 [INFO] Sending to ptd: 'Stop'
02-23-2021 18:45:49.435ptd-server 2021-02-23 18:45:49,435 [INFO] Reply from ptd: 'Stopping untimed measurement'
: Response to client sent: Stopping untimed measurement
ptd-server 2021-02-23 18:45:49,446 [ERROR] Got an exception
Traceback (most recent call last):
  File "C:\cygwin64\home\lab\mlperf\power-dev\ptd_client_server\lib\server.py", line 528, in handle_connection
    reply = self._handle_cmd(cmd, p)
  File "C:\cygwin64\home\lab\mlperf\power-dev\ptd_client_server\lib\server.py", line 594, in _handle_cmd
    return unbool[self.session.stop(Mode.RANGING)]
  File "C:\cygwin64\home\lab\mlperf\power-dev\ptd_client_server\lib\server.py", line 804, in stop
    start_channel = int(self._server._config.ptd_channel[0])
ValueError: invalid literal for int() with base 10: '(2'
```

**Comment by dmiskovic-NV** [comment]
List of multichannel devices: 48 (Yokogawa WT500), 59 (Hioki PW3336), 61 (Hioki PW3337), 77 (Yokogawa WT332/WT333)

**Comment by Lilit1122** [comment]
Thank you for the report. Could you check the changes?

**Comment by dmiskovic-NV** [comment]
verified it works
```
ptd-server 2021-02-25 07:42:15,207 [CRITICAL] server.cfg: 'channel' value should consist of one number or be disabled for a 1-channel device 52.
PS C:\cygwin64\home\lab\mlperf\power-dev\ptd_client_server> python server.py -c server.cfg
ptd-server 2021-02-25 07:42:33,648 [CRITICAL] server.cfg: 'channel' value should consist of two numbers for a multichannel device 77.
```

thanks
