### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by rakshithvasudev** [mlcommons/power-dev#247]
Hello All,

**Summary :**
I'm trying to validate the current `master` (https://github.com/mlcommons/power-dev/commit/5e3dbeab467fc7c98a8b564c92f1608369d84683)  branch's workflow. I'm running this with our new `Yokogawa WT333E` multichannel meter. It's erroring out with an index out of range error as follows, on our NVIDIA code workflow based submission (error below).

When I launch resnet50 server inference workload for example with the following client and server settings, it runs the benchmark and is not generating any power related log files inside the `--output` folder. 

`run_workload.sh` file
```
#!/bin/bash
set -ex

make run_harness RUN_ARGS="--fast --benchmarks=resnet50 --log_dir build/logs/power --scenarios=Server --config_ver=default --test_mode=PerformanceOnly"

```

`run_power.sh` file
```
#!/bin/bash
set -ex

python3.7 power-dev/ptd_client_server/client.py \
        --addr 10.141.168.1 \
        --output "./cout" \
        --run-workload "./run_workload.sh" \
        --ntp 100.64.0.18 \
        --loadgen-logs "/work/build/logs/power/R750xa_A100-PCIE-80GBx4_TRT/resnet50/Server" \
        --label "resnetserver" \
```

IndexError: list index out of range
```
....
....
07-18-2021 02:43:20.902: WARNING: Uncertainty unknown for the last measurement sample! channel 2
07-18-2021 02:43:21.902: ERROR: Can't evaluate uncertainty of this sample!
07-18-2021 02:43:21.902: WARNING: Uncertainty unknown for the last measurement sample! channel 1
07-18-2021 02:43:21.902: ERROR: Can't evaluate uncertainty of this sample!
07-18-2021 02:43:21.902: WARNING: Uncertainty unknown for the last measurement sample! channel 2
ptd-server 2021-07-17 21:43:21,980 [INFO] Got command from the client 'session,2021-07-17_21-41-18_resnetserver,stop,ranging'
07-18-2021 02:43:22.902: ERROR: Can't evaluate uncertainty of this sample!
07-18-2021 02:43:22.902: WARNING: Uncertainty unknown for the last measurement sample! channel 1
07-18-2021 02:43:22.902: ERROR: Can't evaluate uncertainty of this sample!
07-18-2021 02:43:22.903: WARNING: Uncertainty unknown for the last measurement sample! channel 2
07-18-2021 02:43:23.902: ERROR: Can't evaluate uncertainty of this sample!
07-18-2021 02:43:23.902: WARNING: Uncertainty unknown for the last measurement sample! channel 1
07-18-2021 02:43:23.903: ERROR: Can't evaluate uncertainty of this sample!
07-18-2021 02:43:23.903: WARNING: Uncertainty unknown for the last measurement sample! channel 2
07-18-2021 02:43:24.902: ERROR: Can't evaluate uncertainty of this sample!
07-18-2021 02:43:24.902: WARNING: Uncertainty unknown for the last measurement sample! channel 1
07-18-2021 02:43:24.902: ERROR: Can't evaluate uncertainty of this sample!
07-18-2021 02:43:24.902: WARNING: Uncertainty unknown for the last measurement sample! channel 2
07-18-2021 02:43:25.902: ERROR: Can't evaluate uncertainty of this sample!
07-18-2021 02:43:25.902: WARNING: Uncertainty unknown for the last measurement sample! channel 1
07-18-2021 02:43:25.902: ERROR: Can't evaluate uncertainty of this sample!
07-18-2021 02:43:25.902: WARNING: Uncertainty unknown for the last measurement sample! channel 2
07-18-2021 02:43:26.902: ERROR: Can't evaluate uncertainty of this sample!
07-18-2021 02:43:26.902: WARNING: Uncertainty unknown for the last measurement sample! channel 1
07-18-2021 02:43:26.902: ERROR: Can't evaluate uncertainty of this sample!
07-18-2021 02:43:26.902: WARNING: Uncertainty unknown for the last measurement sample! channel 2
07-18-2021 02:43:27.902: ERROR: Can't evaluate uncertainty of this sample!
07-18-2021 02:43:27.902: WARNING: Uncertainty unknown for the last measurement sample! channel 1
07-18-2021 02:43:27.902: ERROR: Can't evaluate uncertainty of this sample!
07-18-2021 02:43:27.902: WARNING: Uncertainty unknown for the last measurement sample! channel 2
07-18-2021 02:43:28.902: ERROR: Can't evaluate uncertainty of this sample!
07-18-2021 02:43:28.902: WARNING: Uncertainty unknown for the last measurement sample! channel 1
07-18-2021 02:43:28.902: ERROR: Can't evaluate uncertainty of this sample!
07-18-2021 02:43:28.902: WARNING: Uncertainty unknown for the last measurement sample! channel 2
07-18-2021 02:43:29.902: ERROR: Can't evaluate uncertainty of this sample!
07-18-2021 02:43:29.902: WARNING: Uncertainty unknown for the last measurement sample! channel 1
07-18-2021 02:43:29.902: ERROR: Can't evaluate uncertainty of this sample!
07-18-2021 02:43:29.902: WARNING: Uncertainty unknown for the last measurement sample! channel 2
07-18-2021 02:43:30.902: ERROR: Can't evaluate uncertainty of this sample!
07-18-2021 02:43:30.902: WARNING: Uncertainty unknown for the last measurement sample! channel 1
07-18-2021 02:43:30.902: ERROR: Can't evaluate uncertainty of this sample!
07-18-2021 02:43:30.902: WARNING: Uncertainty unknown for the last measurement sample! channel 2
07-18-2021 02:43:31.902: ERROR: Can't evaluate uncertainty of this sample!
07-18-2021 02:43:31.902: WARNING: Uncertainty unknown for the last measurement sample! channel 1
07-18-2021 02:43:31.902: ERROR: Can't evaluate uncertainty of this sample!
07-18-2021 02:43:31.903: WARNING: Uncertainty unknown for the last measurement sample! channel 2
ptd-server 2021-07-17 21:43:31,980 [INFO] Sending to ptd: 'Stop'
07-18-2021 02:43:31.980ptd-server 2021-07-17 21:43:31,980 [INFO] Reply from ptd: 'Stopping untimed measurement'
: Response to client sent: Stopping untimed measurement
ptd-server 2021-07-17 21:43:31,980 [ERROR] Got an exception
Traceback (most recent call last):
  File "..\ptd_client_server\lib\server.py", line 576, in handle_connection
    reply = self._handle_cmd(cmd, p)
  File "..\ptd_client_server\lib\server.py", line 649, in _handle_cmd
    return unbool[self.session.stop(Mode.RANGING)]
  File "..\ptd_client_server\lib\server.py", line 860, in stop
    self._maxVolts, self._maxAmps = max_volts_amps(
  File "..\ptd_client_server\lib\server.py", line 165, in max_volts_amps
    if not parser.check(f"Ch{channel_range[0]}"):
IndexError: list index out of range
ptd-server 2021-07-17 21:43:31,980 [INFO] Sending reply to client 'Error: exception'
ptd-server 2021-07-17 21:43:31,980 [INFO] Connection closed
ptd-server 2021-07-17 21:43:31,980 [WARNING] Client connection closed unexpectedly
ptd-server 2021-07-17 21:43:31,980 [INFO] Sending to ptd: 'Stop'
07-18-2021 02:43:32.730: Completed test
07-18-2021 02:43:32.730: Avg watts 1623.218947, min watts 983.800000, max watts 1979.000000, samples 95, errors 0, valid 95
ptd-server 2021-07-17 21:43:32,730 [INFO] Reply from ptd: 'Error: no measurement to stop'
07-18-2021 02:43:32.730: Response to client sent: Error: no measurement to stop
ptd-server 2021-07-17 21:43:32,730 [INFO] Sending to ptd: 'SR,V,Auto'
07-18-2021 02:43:37.746: Volt range set to Auto
07-18-2021 02:43:37.809ptd-server 2021-07-17 21:43:37,808 [INFO] Reply from ptd: 'Range V changed'
: Response to client sent: Range V changed
ptd-server 2021-07-17 21:43:37,808 [INFO] Sending to ptd: 'SR,A,Auto'
07-18-2021 02:43:42.824: Ampere range set to Auto
07-18-2021 02:43:42.887ptd-server 2021-07-17 21:43:42,887 [INFO] Reply from ptd: 'Range A changed'
: Response to client sent: Range A changed
ptd-server 2021-07-17 21:43:42,887 [INFO] Set initial values for Amps Auto and Volts Auto
ptd-server 2021-07-17 21:43:42,887 [INFO] Stopping ptd...
07-18-2021 02:43:42.888: No data returned by socket read.
07-18-2021 02:43:42.888: Shutting connection down...
07-18-2021 02:43:42.888: Connection is down.
07-18-2021 02:43:42.888: Waiting for a connection...
ptd-server 2021-07-17 21:43:42,902 [INFO] Done processing
```

Here is my server.conf file:

```
# Server Configuration Template
# To use change the section of the config that you'd like to change.

[server]
# NTP server to sync with before each measurement.
# See "NTP" section in the README.md.
ntpServer: 100.64.0.18

# A directory to store output data. A relative or absolute path could be used.
# A new subdirectory will be created per each run.
# The name of this sub-directory consists of date, time, label, and mode (ranging/testing).
# The loadgen log is fetched from the client if the `--send-logs` option is enabled for the client.
# The name of the directory is determined by the workload script running on the SUT, e.g. `ssdmobilenet`.
# The power log, named `spl.txt`, is extracted from the full PTDaemon log (`ptdLogfile`)
#outDir: D:\ptd-logs-new\

# (Optional) IP address and port that server listen on
# Defaults to "0.0.0.0 4950" if not set
#listen: 192.168.1.2 4950


# PTDaemon configuration.
# The following options are mapped to PTDaemon command line arguments.
# Please refer to SPEC PTDaemon Programmers Guide or `ptd -h` for the details.
[ptd]
# A path to PTDaemon executable binary.
ptd: D:\PTD\ptd-windows-x86.exe

# A path to a logfile that PTDaemon produces (`-l` option).
# Note that in the current implementation this file is considered temporary
# and may be overwritten.
#logFile: logs_ptdeamon.txt

# (Optional) A port on that PTDaemon listens (`-p` option). Default is 8888.
#networkPort: 8888

# Power Analyzer numerical device type. Refer to `ptd -h` for the full list.
# 49 corresponds to Yokogawa WT310.
deviceType: 77

# interfaceFlag and devicePort describe the physical connection to the analyzer.
# interfaceFlag is either one of -n, -g, -y, -U, or empty.
# Refer to SPEC PTDaemon Programmers Guide or `ptd -h` for the details.
# Below are some examples of interfaceFlag and devicePort pairs.

# Use RS232 interface.
# Empty interfaceFlag corresponds to RS232.
#interfaceFlag:
#devicePort: COM1

# Use GPIB interface.
#interfaceFlag: -g
#devicePort: 0

# Set GPIB board number (`-b` option)
#gpibBoard: 0

# Use TCPIPv4 ethernet interface.
#interfaceFlag: -n
#devicePort: 192.168.1.123

# Use Yokogawa TMCTL for USB or ethernet interface.
# devicePort should be either the IP address or device serial number.
interfaceFlag: -y
# I have the correct value in there
devicePort: C2XXXXXX

# (Optional) Channel number for multichannel analyzers operating in single channel mode. (`-c` option)
# Channel value should consist of two numbers separated by a comma for a multichannel analyzer.
# Channel value should consist of one number or be disabled for a 1-channel analyzer.
channel: 1,2
```

It runs the workload benchmark and it doesn't create any files in the `cout `directory (inside the client) other than just the directories as seen below: 

```
(mlperf) rakshith@mlperf-inference-rakshith:/work/cout$ tree
.
└── 2021-07-17_21-41-18_resnetserver
    └── power
```

Here is the error on the client side:

```

....
....
&&&& PASSED Default_Harness # ./build/bin/harness_default
[2021-07-17 21:43:22,117 main.py:280 INFO] Result: result_scheduled_samples_per_sec: 104029, Result is VALID

======================= Perf harness results: =======================

R750xa_A100-PCIE-80GBx4_TRT-default-Server:
    resnet50: result_scheduled_samples_per_sec: 104029, Result is VALID


======================= Accuracy results: =======================

R750xa_A100-PCIE-80GBx4_TRT-default-Server:
    resnet50: No accuracy results in PerformanceOnly mode.

client 2021-07-17 21:43:22,171 [INFO] Sending command to the server: 'session,2021-07-17_21-41-18_resnetserver,stop,ranging'
client 2021-07-17 21:43:32,178 [INFO] Got response: 'Error: exception'
client 2021-07-17 21:43:32,179 [CRITICAL] Got an unexpecting response from the server

```
Other things I tried:
1) Ran the test multiple times just to make sure it's not somehow a noisy sample somewhere
2) Made the log dir paths absolute
3) explored with `--force` argument 
4) Verified if indeed inference benchmark loadgen logs exist at `build/logs/power`
5) With and without keeping and `--fast`  

I suspect because it's not creating any log files, it's erroring out with an out of index?

Any suggestions to fix this would be appreciated.

**Comment by trevor-cockrell** [comment]
In `server.py`
https://github.com/mlcommons/power-dev/blob/5e3dbeab467fc7c98a8b564c92f1608369d84683/ptd_client_server/lib/server.py#L162

The `while` loop tries to continue even after it has exhausted the configured channels. Even after it has `channel_range.pop(0)`'ed all available channels, the loop will continue and error out when it tries to manipulate an empty list. 

I found that adding an extra check at the end to break out of the `while` loop allowed me to proceed past this issue. 
```
                while not parser.is_finished():
                    is_sutable_channel = True
                    if not parser.check(f"Ch{channel_range[0]}"):
                        is_sutable_channel = False
                    else:
                        channel_range.pop(0)
                    . . .
                    if len(channel_range)==0:
                        break
```

**Comment by s-idgunji** [comment]
Hi Trevor - Thanks.    @trevor-cockrell   - can you check with @nvpohanh  on how to get a code change in so that this can be fixed.

@rakshithvasudev  - could you use Trevor's workaround to make progress.  We will track and close this with high priority.

**Comment by nvpohanh** [comment]
Will file a PR by EOD

**Comment by nvpohanh** [comment]
will be fixed by #249

**Comment by s-idgunji** [comment]
Thanks Po-Han (@nvpohanh ) . @rakshithvasudev   - Please comment once you have tested.

**Comment by rakshithvasudev** [comment]
Thanks @s-idgunji @trevor-cockrell @nvpohanh

Will keep you updated once I get a chance to test it.

**Comment by rakshithvasudev** [comment]
That fix worked. Additionally I had to update my time zone to UTC thanks to @trevor-cockrell  for that tip.
